language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y protoc
install: "protoc --proto_path=./protocol/ --python_out=. ./protocol/trawler.proto"
script: #??
